# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle (Manual)

on:
  workflow_dispatch:
    inputs:
      ver:
        description: 'Package Version'
        required: true
        default: '1.0'
      mcver:
        description: 'Minecraft Version'
        required: true
        default: '1.16.5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Write version to Properties-file
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: './gradle.properties'
        property: 'modVersion'
        value: '${{ github.event.inputs.ver }}'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: mc${{ github.event.inputs.mcver }}-v${{ github.event.inputs.ver }}
        release_name: Release ${{ github.event.inputs.ver }} for Minecraft ${{ github.event.inputs.mcver }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./build/libs/enhancedmachine-${{ github.event.inputs.ver }}.jar
        asset_name: EnhancedMachine-${{ github.event.inputs.mcver }}-${{ github.event.inputs.ver }}.jar
        asset_content_type: application/zip
